apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: auth
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
  artifacts:
    - image: rohanbennur959/url-shortener-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js
    - image: rohanbennur959/url-shortener-mapper
      context: urlmapper
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js
    - image: rohanbennur959/url-shortener-redirect
      context: urlredirect
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js
    - image: rohanbennur959/url-shortener-frontend
      context: url-shortener-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.js"