apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: rohanbennur959/url-shortener-auth
        ports:
        - containerPort: 3000
        env:
          - name:  JWT_KEY
            valueFrom:
              secretKeyRef:
                name:  auth-jwt-key-secret
                key:  jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name:  auth-cluster-ip-svc
spec:
  selector:
    app:  auth
  type: ClusterIP
  ports:
    - name:  auth
      port:  3000
      targetPort:  3000
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-key-secret
type: Opaque
data:
  jwt-key: cm9oYW4=